name: "!! INITIAL: Migrate Repo Template !!"

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:
    inputs:
      group:
        description: 'Artifact groupId'
        required: true
        default: 'org.acme'
        type: string
      name:
        description: 'Artifact artifactId (recommended to align with repo name)'
        required: true
        default: 'fancy-library-name'
        type: string
      package:
        description: 'Artifact package'
        required: true
        default: 'org.acme.fancy.lib'
        type: string
      email:
        description: 'Contact email (CODE_OF_CONDUCT.md)'
        required: true
        default: 'info@yourdomain.com'
        type: string

jobs:

  migrate_repo_template_1:
    name: Run Migration (part 1)
    runs-on: ubuntu-latest
    if: |
      github.repository != 'thriving-dev/java-library-template'
      && github.event_name == 'workflow_dispatch'

    steps:

      - name: Validate input param 'group'
        env:
          INPUT_PARAM: ${{ inputs.group }}
        run: |
          if [[ ! $INPUT_PARAM =~ ^[a-z0-9]([._]?[a-z0-9]+)*$ ]]; then
            echo "Invalid value for 'group' param: $INPUT_PARAM"
            echo "Must be all lowercase, no whitespaces, no special characters but underscore and dots, no consecutive dots."
            exit 1
          fi
      - name: Validate input param 'name'
        env:
          INPUT_PARAM: ${{ inputs.name }}
        run: |
          if [[ ! $INPUT_PARAM =~ ^[a-z0-9]([_-]?[a-z0-9]+)*$ ]]; then
            echo "Invalid value for 'name': $INPUT_PARAM"
            echo "Must be all lowercase, no whitespaces, no special characters but '-', no leading or consecutive dashes."
            exit 1
          fi
      - name: Validate input param 'package'
        env:
          INPUT_PARAM: ${{ inputs.package }}
        run: |
          if [[ ! $INPUT_PARAM =~ ^[a-z_]([._]?[a-z_][a-z0-9_]*)*$ ]]; then
            echo "Invalid value for 'package': $INPUT_PARAM"
            echo "Must conform to all lowercase, no whitespaces, no special characters but underscore, separated by dots, no consecutive dots, no element beginning with a number."
            exit 1
          fi

      - name: Checkout project sources
        uses: actions/checkout@v4
        with:
          ref: main
          token: ${{ secrets.CI_GITHUB_TOKEN }}

      - name: Migrate
        env:
          GITHUB_REPOSITORY_OLD: "thriving-dev/java-library-template"
          GITHUB_REPOSITORY_NAME: ${{ github.event.repository.name }}
          ARTIFACT_GROUP_OLD: "dev.thriving.oss"
          ARTIFACT_GROUP_NEW: ${{ inputs.group }}
          ARTIFACT_NAME_OLD: "java-library-template"
          ARTIFACT_NAME_NEW: ${{ inputs.name }}
          PACKAGE_OLD: "dev.thriving.oss.java.library.template"
          PACKAGE_NEW: ${{ inputs.package }}
          INPUT_EMAIL: ${{ inputs.email }}
        run: |
          # gradle files
          ## gradle.properties - initial version 
          echo "version=0.0.4-SNAPSHOT" > gradle.properties
          
          # Remove this very GitHub Actions workflow yml
          rm .github/workflows/0.initial.migrate-repo-template.yml

      - name: Commit files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git status
          git commit -m "chore: INITIAL Migrate Repo Template"

      # Push changes
      - name: Push changes
        run: |
          git push origin main
