name: Deploy Javadoc

on:
  workflow_call:

jobs:
  deploy_javadoc:
    name: Build & deploy
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout project sources
        uses: actions/checkout@v4

      - uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '17'
          cache: 'gradle'
      - uses: gradle/wrapper-validation-action@v1
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2.8.0

      - name: Run build (incl. test)
        run: gradle javadoc

      - name: Conclude javadoc version and set env
        run: |
          if [[ "$GITHUB_REF" == "refs/heads/main" || "$GITHUB_REF" == "refs/heads/master" ]]; then
            echo "PUBLISH_VERSION=current" >> $GITHUB_ENV
          else
            echo "PUBLISH_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
          fi

      - name: Deploy to GitHub Page 🚀 with Gradle
        uses: JamesIves/github-pages-deploy-action@v4.4.3
        with:
          branch: gh-pages
          clean: true
          folder: java-library-template/build/docs/javadoc
          target-folder: javadoc/${{ env.PUBLISH_VERSION }}
